language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NRuzUb1iKkKeeFDD+0Z+axZ2kOOBCFZubn7JglSXxfS+3jcoqrCEMcEP/hrQMbXk3J9ZMSOBLO+Y+E9KOSGb3BEMupuXTPpQ5PKBBE/7RRjwlgrRO2K2KzvUwEawxaBeSErC5dQJDw5BPxt0z0T715YjRU7PB6Vk7qWh0x9eTVz9RyqOQXJysrHTK1lcXtH8S+HPK1/yyXWtnscaaAU4MxaGZuW6qL9XVyqb9PCDGzOK3Ii00cIQ1uiV0oySxkrGwPbwohi18o8Jqy80ORwx2iX11w9SEM8MYvCtPeJvZ6PIHKYjCxQDA5nYcYnQ97rtl3JlOqUyVOMOHqAN4iljv8PMlLT7cBRbejD3yndxcFFBu63hdjsxzTrJZkcIyRzouF/QTosSwpUTX/vBDJ3/K47svE2IREVxrozVZH4cpUslOGDAsxaWJdBWefV4OGBNjZ0zTGzjmA9MXE5nhXoxF+TkdxeY2VWLleYv6WRa8vN0hWE0FItQl8K6fVcVAF2FuhqcLkLWH5PTy9ZsSlRwnFdd/NhskYhf7N2SmgJc69woRNJ7V6Ndm7/4uy69eik11rAIVwU9J8vzaMY7aMw3Ew+cdzo/Bwyk3IzKa3dhdV3TqX9oDW991bG4CUeOG73xY3JAfucl/FQdgo820qHVFqe7/YmDN6hiRZDjeGIsk8k=
  file:
    - 'comma-separated-tokens.js'
    - 'comma-separated-tokens.min.js'
  on:
    tags: true
